traits:
  'background':
    NONE: 0
    bkg04: 15
    bkg05: 14
    bkg07: 14
    bkg06: 14
    bkg02: 14
    bkg03: 14
    bkg01: 15
  'race':
    NONE: 0
    american: 10
    bornean: 10
    european: 10
    greater_hog: 10
    honey: 10
    japanese: 10
    javan: 10
    nevadensis: 10
    sunda: 10
    vietnam: 10
  

